### ISSUE TITLE
Add goal and reporting status title/description

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg-site-starter#64]
The site starter is not using these configuration options:

```
goals_page:
    title: title goes here
    description: description goes here
reporting_status:
    title: title goes here
    description: description goes here
```

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @AnnCorp For the title/description on the Goals page and the Reporting Status page - which approach should we take:
1. Use "lorem ipsum" or other placeholder text
2. Create generic but useful titles/descriptions and then translate them

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @AnnCorp @phillipgardiner What about the following:

```
goals_page:
    title: general.goals (Goals)
    description: Click on each goal for statistics for  %name Sustainable Development Goal global indicators. (might be quite easy to get this translated as very similar to frontpage.instructions - just without the search bit)
reporting_status:
    title: status.reporting_status (Reporting status)
    description: Reporting status provides an overview of how much Sustainable Development Goal (SDG) data %name reports. (this would be a completely new translation)
```
